const ROLE_TYPE = Object.freeze({
  USER: "USER",
  ADMIN: "ADMIN",
  HOTEL_STAFF: "HOTEL_STAFF",
  HOTEL_MANAGER: "HOTEL_MANAGER",
});

const BOOKING_STATUS = Object.freeze({
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CANCELLED: "CANCELLED",
});

module.exports = {
  ROLE_TYPE,
  BOOKING_STATUS,
};
